1:
	gcc 1feladat.c -lmingw32 -lSDL2main -lSDL2 -lSDL2_image -lopengl32 -lm -o 1feladat.exe -Wall -Wextra -Wpedantic

2:
	gcc 2feladat.c -lmingw32 -lSDL2main -lSDL2 -lSDL2_image -lopengl32 -lm -o 2feladat.exe -Wall -Wextra -Wpedantic

3:
	gcc 3feladat.c -lmingw32 -lSDL2main -lSDL2 -lSDL2_image -lopengl32 -lm -o 3feladat.exe -Wall -Wextra -Wpedantic

4:
	gcc 4feladat.c -lmingw32 -lSDL2main -lSDL2 -lSDL2_image -lopengl32 -lm -o 4feladat.exe -Wall -Wextra -Wpedantic

5:
	gcc 5feladat.c -lmingw32 -lSDL2main -lSDL2 -lSDL2_image -lopengl32 -lm -o 5feladat.exe -Wall -Wextra -Wpedantic

